ZcrlPortal/Controllers/EditorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZcrlPortal.DAL;
using ZcrlPortal.Models;
using ZcrlPortal.Extensions;

namespace ZcrlPortal.Controllers
{
    [Authorize(Roles="Administrators, Editors, Doctors")]
    public class EditorController : MasterController
    {
        private string getTitleForPage(PublicationType type, CrudMode mode)
        {
            string result = null;

            switch (type)
            {
                case PublicationType.News:
                    {
                        switch (mode)
                        {
                            case CrudMode.Add:
                                {
                                    result = "Створення новини";
                                    break;
                                }
                            case CrudMode.Edit:
                                {
                                    result = "Редагування новину";
                                    break;
                                }
                        }
                        break;
                    }
                case PublicationType.Article:
                    {
                        switch (mode)
                        {
                            case CrudMode.Add:
                                {
                                    result = "Створення статті";
                                    break;
                                }
                            case CrudMode.Edit:
                                {
                                    result = "Редагування статті";
                                    break;
                                }
                        }
                        break;
                    }
            }

            return result;
        }

        public string getModelError(Publication pub)
        {
            string error = null;

            if(string.IsNullOrWhiteSpace(pub.Title))
            {
                error = "Ви не вказали заголовок";
                return error;
            }

            if (string.IsNullOrWhiteSpace(pub.Summary))
            {
                error = "Ви не ввели стислий зміст";
                return error;
            }

            return error;
        }

        [Authorize(Roles="Administrators, Editors")]
        public ActionResult AddNews()
        {
            ViewBag.Title = getTitleForPage(PublicationType.News, CrudMode.Add);

            ViewBag.Mode = CrudMode.Add;

            return View("AddEditItem", new Publication() { InformationType = PublicationType.News, UserProfileId = (int)Profile["Id"] });
        }
        public ActionResult AddArticle()
        {
            ViewBag.Title = getTitleForPage(PublicationType.Article, CrudMode.Add);

            ViewBag.Mode = CrudMode.Add;

            using(zcrlDbContext = new ZcrlContext())
            {
                ViewBag.Themes = (from t in zcrlDbContext.PortalDataGroups 
                                  where (t.RelatedGroup == DataGroupType.ArticleGroup) 
                                  select t).ToList();
            }

            return View("AddEditItem", new Publication() { InformationType = PublicationType.Article, UserProfileId = (int)Profile["Id"] });
        }

        [HttpPost]
        public ActionResult Add(Publication newPublicationItem, HttpPostedFileBase attachedFile, int[] selectedThemes)
        {
            if (User.IsInRole("Doctors") && newPublicationItem.InformationType != PublicationType.Article)
            {
                return RedirectToAction("AccessError", "Error");
            }

            if(newPublicationItem.InformationType == PublicationType.Article)
            {
                using (zcrlDbContext = new ZcrlContext())
                {
                    ViewBag.Themes = (from t in zcrlDbContext.PortalDataGroups
                                      where (t.RelatedGroup == DataGroupType.ArticleGroup)
                                      select t).ToList();
                }
            }

            string redirectActionName = null;
            string publicationTypeName = null;
            LogRecordType recordTypeForLog = LogRecordType.NewsAddEdit;
            string logAddEditItemName = null;

            string error = getModelError(newPublicationItem);
            if(!string.IsNullOrWhiteSpace(error))
            {
                TempData["Error"] = error;
                ViewBag.Mode = CrudMode.Add;
                ViewBag.Title = getTitleForPage(newPublicationItem.InformationType, CrudMode.Add);
                return View("AddEditItem", newPublicationItem);
            }
            if (!attachedFile.IsImage() && attachedFile != null)
            {
                TempData["Error"] = "Невірний формат зображення для заголовку";
                ViewBag.Mode = CrudMode.Add;
                ViewBag.Title = getTitleForPage(newPublicationItem.InformationType, CrudMode.Add);
                return View("AddEditItem", newPublicationItem);
            }

            // Получаем максимально допустимую длинну заголовка новости
            System.ComponentModel.DataAnnotations.MaxLengthAttribute[] maxLengthAttribs = Attribute.GetCustomAttributes(typeof(Publication).GetProperty("Title"),
                typeof(System.ComponentModel.DataAnnotations.MaxLengthAttribute)) as System.ComponentModel.DataAnnotations.MaxLengthAttribute[];
            int maxTitleLength = maxLengthAttribs.Length > 0 ? maxLengthAttribs.Last().Length : 0;

            if ((maxTitleLength > 0) && (newPublicationItem.Title.Length > maxTitleLength))
            {
                TempData["Error"] = "Максимально допустима довжина заголовку " + maxTitleLength + " символів";
                ViewBag.Mode = CrudMode.Add;
                ViewBag.Title = getTitleForPage(newPublicationItem.InformationType, CrudMode.Add);
                return View("AddEditItem", newPublicationItem);
            }

            using (zcrlDbContext = new ZcrlContext())
            {
                if(attachedFile != null)
                {
                    try
                    {
                        string uploadImgName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(attachedFile.FileName);
                        string uploadImgPath = System.IO.Path.Combine(Server.MapPath(UPLOADFILE_DIR), uploadImgName);

                        attachedFile.SaveAs(uploadImgPath);
                        newPublicationItem.TitleImage = uploadImgName;
                    }
                    catch
                    {
                        TempData["Error"] = "Помилка завантаження зображення";
                        ViewBag.Mode = CrudMode.Add;
                        ViewBag.Title = getTitleForPage(newPublicationItem.InformationType, CrudMode.Add);
                        return View("AddEditItem", newPublicationItem);
                    }
                }

                newPublicationItem.PublicationDate = DateTime.Now;
                newPublicationItem.Title = newPublicationItem.Title.Trim();

                zcrlDbContext.PortalPublications.Add(newPublicationItem);

                if ((newPublicationItem.InformationType == PublicationType.Article) && (selectedThemes != null))
                {
                    newPublicationItem.Themes.Clear();
                    foreach (int theme in selectedThemes)
                    {
                        var requiredTheme = (from t in zcrlDbContext.PortalDataGroups
                                             where ((t.RelatedGroup == DataGroupType.ArticleGroup) && (t.Id == theme))
                                             select t).FirstOrDefault();
                        if (requiredTheme != null)
                        {
                            newPublicationItem.Themes.Add(requiredTheme);
                        }
                    }
                }

                zcrlDbContext.SaveChanges();
                

                switch(newPublicationItem.InformationType)
                {
                    case PublicationType.Article:
                        {
                            redirectActionName = "Articles";
                            publicationTypeName = "Стаття";
                            recordTypeForLog = LogRecordType.ArticlesAddEdit;
                            logAddEditItemName = "статтю";
                            break;
                        }
                    case PublicationType.News:
                        {
                            redirectActionName = "News";
                            publicationTypeName = "Новина";
                            recordTypeForLog = LogRecordType.NewsAddEdit;
                            logAddEditItemName = "новину";
                            break;
                        }
                }

                zcrlDbContext.LogJournal.Add(new LogRecord() 
                { 
                    СreatedDate = DateTime.Now, RecordType = recordTypeForLog,
                    Content = string.Format("Користувач <b>{0} {1}.{2}.</b> додав нову {3} <b>{4}</b>", 
                    (string)Profile["LastName"], ((string)Profile["FirstName"]).First(), ((string)Profile["MiddleName"]).First(), 
                    logAddEditItemName, newPublicationItem.Title)
                });

                zcrlDbContext.SaveChanges();

                TempData["SuccessMessage"] = publicationTypeName + " успішно створена";
                return RedirectToAction(redirectActionName, "Home");
            }
        }

        public ActionResult Edit(int? id)
        {
            using(zcrlDbContext = new DAL.ZcrlContext())
            {
                if(!id.HasValue)
                {
                    return RedirectToAction("NotFound", "Error");
                }

                var requiredNewsItem = (from n in zcrlDbContext.PortalPublications.Include("Themes") 

ZcrlPortal/Views/Editor/AddEditItem.cshtml
@using ZcrlPortal.Controllers
@using ZcrlPortal.Models
@model Publication
@{
    List<DataGroup> articleThemes = ViewBag.Themes;
        
    string actionName = null;
    CrudMode mode = ViewBag.Mode;
     
    switch(mode)
    {
        case CrudMode.Add:
            {
                actionName = "Add";
                break;
            }
        case CrudMode.Edit:
            {
                actionName = "Edit";
                break;
            }
    }
    
    Layout = "~/Views/Shared/_main.cshtml";
}

<div class="editProfileContainer">
    @if (!string.IsNullOrWhiteSpace((string)TempData["Error"]))
    {
        <div class="errorMessage">@TempData["Error"]</div>
    }
    @if (!string.IsNullOrWhiteSpace((string)TempData["SuccessMessage"]))
    {
        <div class="successMessage">@TempData["SuccessMessage"]</div>
    }

    @using (Html.BeginForm(actionName, "Editor", FormMethod.Post, new { @class = "smart-green", enctype = "multipart/form-data" }))
    {
        @Html.HiddenFor(m => m.UserProfileId)
        
        if (mode == CrudMode.Edit)
        {
            Html.HiddenFor(m => m.Id);
        }

        @Html.HiddenFor(m => m.InformationType)

        <table style="width: 100%;">
            <tr>
                <th>Заголовок:</th>
                <td>@Html.TextBoxFor(m => m.Title)</td>
            </tr>
            <tr>
                <th>Картинка для заголовку:</th>
                <td>
                    <input type="text" class="ufName" readonly="readonly" id="ufName" /> <div class="uploadFileContainer"><span>Вибрати файл</span><input name="attachedFile" id="attachedFile" type="file" onchange="GetUploadFileName(this)" /></div> 
                    @if(!string.IsNullOrWhiteSpace(Model.TitleImage))
                    {
                       <a href="@Url.Action("DeleteTitleImg", "Editor", new { imgId = Model.Id })">Видалити картинку</a>
                    }
                </td>
            </tr>
            <tr>
                <th>Стислий зміст:</th>
                <td>@Html.TextAreaFor(m => m.Summary, new { style = "height:60px; width:350px;"})</td>
            </tr>
            <tr>
            @if(Model.InformationType == PublicationType.Article)
            {
                <tr>
                    <th>Теми статті:</th>
                    <td>@foreach (var theme in articleThemes)
                        {
                            <input type="checkbox" name="selectedThemes" value="@theme.Id" @(Model.Themes.Contains(theme) ? "checked=\"checked\"" : "")> @theme.Name <br />
                        }
                    </td>
                </tr>   
            }
            <tr>
                <td colspan="2"><br /></td>
            </tr>
            <tr>
                <td colspan="2">@Html.TextAreaFor(m => m.Content)</td>
            </tr>
            <tr>
                <th colspan="2" style="text-align: center;">
                    <button type="submit">
                        @if (mode == CrudMode.Edit)
                        {
                            @:Змінити данні
                        }
                        else
                        {
                            @:Створити
                        }
                    </button>
                </th>
            </tr>
        </table>
    }
</div>

<script>
    CKEDITOR.replace('Content', {
         toolbar: [
         { name: 'clipboard', groups: ['clipboard', 'undo'], items: ['Cut', 'Copy', 'Paste', '-', 'Undo', 'Redo'] },
         { name: 'editing', groups: ['find', 'selection', 'spellchecker'], items: ['Find', 'Replace', '-', 'Maximize'] },
         '/',
         { name: 'basicstyles', groups: ['basicstyles', 'cleanup'], items: ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-','RemoveFormat'] },
         { name: 'paragraph', groups: ['list', 'indent', 'blocks', 'align', 'bidi'], items: ['NumberedList', 'BulletedList', '-', 'Blockquote'] },
         { name: 'links', items: ['Link', 'Image', 'Anchor', 'Table', 'TextColor'] },
         { name: 'styles', items: ['Format'] },
         ],
        filebrowserImageUploadUrl: '@Url.Action("UploadImage", "Editor")',
        format_tags: 'p;h2',
        image2_alignClasses: ['image-left', 'image-center', 'image-right'],
    });
</script>

ZcrlPortal/Views/Editor/EditStaticChapters.cshtml
@using ZcrlPortal.Models
@model StaticChapter
@{
    Layout = "~/Views/Shared/_main.cshtml";
}

<div class="userBio">
    @using (Html.BeginForm("ChangeChapter", "Editor", FormMethod.Post))
    {
        <br />
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.ChapterType)
        @Html.TextAreaFor(m => m.Content)
        <h1 style="text-align: center"><button type="submit">Зберегти зміни</button></h1>
    }
</div>

<script>
    CKEDITOR.replace('Content', {
         toolbar: [
         { name: 'clipboard', groups: ['clipboard', 'undo'], items: ['Cut', 'Copy', 'Paste', '-', 'Undo', 'Redo'] },
         { name: 'editing', groups: ['find', 'selection', 'spellchecker'], items: ['Find', 'Replace', '-', 'Maximize'] },
         '/',
         { name: 'basicstyles', groups: ['basicstyles', 'cleanup'], items: ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-','RemoveFormat'] },
         { name: 'paragraph', groups: ['list', 'indent', 'blocks', 'align', 'bidi'], items: ['NumberedList', 'BulletedList', '-', 'Blockquote'] },
         { name: 'links', items: ['Link', 'Image', 'Anchor', 'Table', 'TextColor'] },
         { name: 'styles', items: ['Format'] },
         ],
        filebrowserImageUploadUrl: '@Url.Action("UploadImage", "Editor")',
        format_tags: 'p;h2',
        image2_alignClasses: ['image-left', 'image-center', 'image-right'],
    });
</script>