ZcrlPortal/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZcrlPortal.Models;

namespace ZcrlPortal.Controllers
{
    [Authorize(Roles = "Administrators, Editors, Doctors, TenderGroup")]
    public class GroupController : MasterController
    {
        private string getTitleForPage(DataGroupType type, CrudMode mode)
        {
            string result = null;

            switch(type)
            {
                case DataGroupType.ArticleGroup:
                    {
                        switch(mode)
                        {
                            case CrudMode.Add:
                                {
                                    result = "Створити нову категорію статей";
                                    break;
                                }
                            case CrudMode.Edit:
                                {
                                    result = "Редагувати категорію";
                                    break;
                                }
                        }
                        break;
                    }
                case DataGroupType.TenderGroup:
                    {
                        switch (mode)
                        {
                            case CrudMode.Add:
                                {
                                    result = "Створити нову тендерну категорію";
                                    break;
                                }
                            case CrudMode.Edit:
                                {
                                    result = "Редагувати категорію";
                                    break;
                                }
                        }
                        break;
                    }
                case DataGroupType.UserDepartment:
                    {
                        switch (mode)
                        {
                            case CrudMode.Add:
                                {
                                    result = "Створити нову группу користувачів";
                                    break;
                                }
                            case CrudMode.Edit:
                                {
                                    result = "Редагувати группу користувачів";
                                    break;
                                }
                        }
                        break;
                    }
            }

            return result;
        }

        private string getModelError(DataGroup dgt)
        {
            string error = null;

            if(string.IsNullOrWhiteSpace(dgt.Name))
            {
                error = "Вы не вказали назву";
                return error;
            }

            string groupName = dgt.Name.Trim();
            using(zcrlDbContext = new DAL.ZcrlContext())
            {
                var existGroup = (from g in zcrlDbContext.PortalDataGroups 
                                  where ((g.RelatedGroup == dgt.RelatedGroup) && (g.Name == dgt.Name)) 
                                  select g).FirstOrDefault();
                if(existGroup != null)
                {
                    error = "Така назва вже існує";
                    return error;
                }
            }

            return error;
        }

        private bool checkUserAccess(DataGroupType dgt, out string redirectActionName, out string editedEntityName)
        {
            redirectActionName = null;
            editedEntityName = null;

            switch (dgt)
            {
                case DataGroupType.UserDepartment:
                    {
                        if (!User.IsInRole("Administrators"))
                        {
                            return false;
                        }
                        redirectActionName = "UserGroups";
                        editedEntityName = "Группа користувачів";

                        break;
                    }
                case DataGroupType.TenderGroup:
                    {
                        if (!User.IsInRole("Administrators") && !User.IsInRole("TenderGroup"))
                        {
                            return false;
                        }
                        redirectActionName = "TenderGroups";
                        editedEntityName = "Тендерна категорія";

                        break;
                    }
                case DataGroupType.ArticleGroup:
                    {
                        if (!User.IsInRole("Administrators") && !User.IsInRole("Editors") && !User.IsInRole("Doctors"))
                        {
                            return false;
                        }
                        redirectActionName = "ArticleGroups";
                        editedEntityName = "Категорія статей";

                        break;
                    }
            }

            return true;
        }

        private List<DataGroup> getGroupsList(DataGroupType groupType)
        {
            using (zcrlDbContext = new DAL.ZcrlContext())
            {
                List<DataGroup> groupsList = (from tg in zcrlDbContext.PortalDataGroups
                                              where (tg.RelatedGroup == groupType)
                                              select tg).ToList();

                return groupsList;
            }
        }

        [Authorize(Roles = "Administrators, TenderGroup")]
        public ActionResult TenderGroups()
        {
            ViewBag.Title = "Тендерні категорії";
            ViewBag.ActionName = "AddTenderGroup";
            return View("GroupsList", getGroupsList(DataGroupType.TenderGroup));
        }

        [Authorize(Roles = "Administrators")]
        public ActionResult UserGroups()
        {
            ViewBag.Title = "Группи користувачів";
            ViewBag.ActionName = "AddUsersGroup";
            return View("GroupsList", getGroupsList(DataGroupType.UserDepartment));
        }

        [Authorize(Roles = "Administrators, Editors, Doctors")]
        public ActionResult ArticleGroups()
        {
            ViewBag.Title = "Категорії статей";
            ViewBag.ActionName = "AddArticleGroup";
            return View("GroupsList", getGroupsList(DataGroupType.ArticleGroup));
        }

        [Authorize(Roles = "Administrators, TenderGroup")]
        public ActionResult AddTenderGroup()
        {
            ViewBag.Title = getTitleForPage(DataGroupType.TenderGroup, CrudMode.Add);
            ViewBag.Mode = CrudMode.Add;
            return View("AddEditGroup", new DataGroup() { RelatedGroup = DataGroupType.TenderGroup });
        }

        [Authorize(Roles = "Administrators")]
        public ActionResult AddUsersGroup()
        {
            ViewBag.Title = getTitleForPage(DataGroupType.UserDepartment, CrudMode.Add);
            ViewBag.Mode = CrudMode.Add;
            return View("AddEditGroup", new DataGroup() { RelatedGroup = DataGroupType.UserDepartment });
        }

        [Authorize(Roles = "Administrators, Editors, Doctors")]
        public ActionResult AddArticleGroup()
        {
            ViewBag.Title = getTitleForPage(DataGroupType.ArticleGroup, CrudMode.Add);
            ViewBag.Mode = CrudMode.Add;
            return View("AddEditGroup", new DataGroup() { RelatedGroup = DataGroupType.ArticleGroup });
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Add(DataGroup newGroup)
        {
            string redirectActionName = null;
            string editedEntityName = null;
            LogRecordType recordTypeForLog = LogRecordType.UserChanges;
            string logAddEditItemName = null;

            string error = getModelError(newGroup);
            if(!string.IsNullOrWhiteSpace(error))
            {
                ViewBag.Mode = CrudMode.Add;
                ViewBag.Title = getTitleForPage(newGroup.RelatedGroup, CrudMode.Add);
                TempData["Error"] = error;
                return View("AddEditGroup", newGroup);
            }

            using(zcrlDbContext = new DAL.ZcrlContext())
            {
                if (!checkUserAccess(newGroup.RelatedGroup, out redirectActionName, out editedEntityName))
                {
                    return RedirectToAction("AccessError", "Error");
                }

                newGroup.Name = newGroup.Name.Trim();
                zcrlDbContext.PortalDataGroups.Add(newGroup);

                switch(newGroup.RelatedGroup)
                {
                    case DataGroupType.UserDepartment:
                        {
                            recordTypeForLog = LogRecordType.UserChanges;
                            logAddEditItemName = "группу користувачів";
                            break;
                        }
                    case DataGroupType.TenderGroup:
                        {
                            recordTypeForLog = LogRecordType.TendersAddEdit;
                            logAddEditItemName = "тендерну категорію";
                            break;
                        }
                    case DataGroupType.ArticleGroup:
                        {
                            recordTypeForLog = LogRecordType.ArticlesAddEdit;
                            logAddEditItemName = "категорію статей";
                            break;
                        }
                }

                zcrlDbContext.LogJournal.Add(new LogRecord()
                {
                    СreatedDate = DateTime.Now,
                    RecordType = recordTypeForLog,
                    Content = string.Format("Користувач <b>{0} {1}.{2}.</b> додав нову {3} <b>{4}</b>",
                    (string)Profile["LastName"], ((string)Profile["FirstName"]).First(), ((string)Profile["MiddleName"]).First(),
                    logAddEditItemName, newGroup.Name)
                });

                zcrlDbContext.SaveChanges();

ZcrlPortal/Views/Group/AddEditGroup.cshtml
@using ZcrlPortal.Models
@using ZcrlPortal.Controllers
@model DataGroup
@{
    Layout = "~/Views/Shared/_main.cshtml";
    CrudMode mode = ViewBag.Mode;
    string actionName = null;
    
    switch(mode)
    {
        case CrudMode.Add:
            {
                actionName = "Add";
                break;
            }
        case CrudMode.Edit:
            {
                actionName = "Edit";
                break;
            }
    }
}
<div class="editProfileContainer">
    @if (!string.IsNullOrWhiteSpace((string)TempData["Error"]))
    {
        <div class="errorMessage">@TempData["Error"]</div>
    }

    @using (Html.BeginForm(actionName, "Group", FormMethod.Post, new { @class = "smart-green" }))
    {
        if (mode == CrudMode.Edit)
        {
            Html.HiddenFor(m => m.Id);
        }
        
        @Html.HiddenFor(m => m.RelatedGroup)
        
        <table>
            <tr>
                <th>Назва:</th>
                <td>@Html.TextBoxFor(m => m.Name, new { placeholder = "Введіть назву типу данних" })</td>
            </tr>
            <tr>
                <th colspan="2" style="text-align: center;">
                    <button type="submit">
                        @if (mode == CrudMode.Edit)
                        {
                            @:Змінити данні
                        }
                        else
                        {
                            @:Створити запис
                        }
                    </button>
                </th>
            </tr>
        </table>
    }
</div>

ZcrlPortal/Views/Group/GroupsList.cshtml
@using ZcrlPortal.Models
@model List<DataGroup>
@{
    Layout = "~/Views/Shared/_main.cshtml";
    string actionName = ViewBag.ActionName;
}

<div class="accountDataContainer">
    @if (!string.IsNullOrWhiteSpace((string)TempData["SuccessMessage"]))
    {
        <div class="successMessage">@TempData["SuccessMessage"]</div>
    }
    <a href="@Url.Action(actionName, "Group")" class="addButton">Додати</a>
    <table>
        <tr>
            <th style="width: 5%">№</th>
            <th style="width: 50%">Назва</th>
            <th style="width: 25%">Дія</th>
        </tr>
        @if (Model.Count == 0)
        {
            <tr><td colspan="3" style="text-align: center;"><i>Записів немає</i></td></tr>
        }
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr>
                <td>@(i + 1)</td>
                <td>@Model[i].Name</td>
                <td><a href="@Url.Action("Edit", "Group", new { id = Model[i].Id })">Редагувати</a> | <a href="@Url.Action("Delete", "Group", new { id = Model[i].Id })" onclick="return confirm('Вы впевнені, що хочете видалити @Model[i].Name?')">Видалити</a></td>
            </tr>
        }
    </table>
</div>