ZcrlPortal/Models/UserProfile.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ZcrlPortal.Models
{
    public enum UserSex
    {
        Male, Female
    }
    public class UserProfile
    {
        public UserProfile()
        {
            ViewPriority = 10000;
            Sex = UserSex.Female;
        }

        public UserProfile(RegistrationRequest request)
        {
            ViewPriority = 10000;

            LastName = request.LastName;
            FirstName = request.FirstName;
            MiddleName = request.MiddleName;
            Sex = request.Sex;

            JobTitle = request.JobTitle;
            TelephoneNumber = request.TelephoneNumber;
            
            if(Email != null)
            {
                Email = request.Email.ToLower();
            }

            SiteAddress = request.SiteAddress;
            WorkLocation = request.WorkLocation;

            Education = request.Education;
            IsPublicated = false;

            RelatedUser = ZcrlPortal.SecurityProviders.ZcrlMembershipProvider.CreateUser(request.Login, request.Password);
        }

        public int Id { get; set; }

        public virtual User RelatedUser { get; set; }
        public int UserId { get; set; }

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }

        public UserSex Sex { get; set; }

        // Рабочий номер телефона
        public string TelephoneNumber { get; set; }

        public string SiteAddress { get; set; }

        public string Education { get; set; }

        public string Email { get; set; }

        // Местонахождение сотрудника
        public string WorkLocation { get; set; }

        // Должность
        public string JobTitle { get; set; }

        // Должен ли публиковатся в списке персонала данный профиль
        public bool IsPublicated { get; set; }

        public string AboutMe { get; set; }

        public string PhotoFileName { get; set; }

        // Группа сотрудников к которой относится профиль
        public virtual DataGroup RelatedDepartment { get; set; }
        public int? DataGroupId { get; set; }

        [Range(1, 10000)]
        public int ViewPriority { get; set; }
    }
}

ZcrlPortal/Controllers/UserProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.IO;
using ZcrlPortal.DAL;
using ZcrlPortal.Extensions;

namespace ZcrlPortal.Controllers
{
    public class UserProfileController : MasterController
    {
        private string getLogString(string changedParamName, 
                                    ZcrlPortal.Models.UserProfile source, 
                                    ZcrlPortal.Models.UserProfile updatedProfile,
                                    string firstValue,
                                    string lastValue,
                                    bool isOwner)
        {
            if (isOwner)
            {
                return string.Format("Користувач <b>{0} {1}.{2}.</b> змінив {3} з <b>{4}</b> на <b>{5}</b>.<br />", 
                     source.LastName, source.FirstName.First(), source.MiddleName.First(), changedParamName,
                     firstValue, lastValue);
            }
            else
            {
                return string.Format("Користувач <b>{0} {1}.{2}.</b> змінив {3} користувача <b>{4} {5}.{6}.</b> з <b>{7}</b> на <b>{8}</b>.<br />", 
                    Profile["LastName"], ((string)Profile["FirstName"]).First(), ((string)Profile["MiddleName"]).First(), changedParamName,
                    updatedProfile.LastName, updatedProfile.FirstName.First(), updatedProfile.MiddleName.First(),
                    firstValue, lastValue);
            }
        }

        private void logProfileChanges(ZcrlPortal.Models.UserProfile source,
                                       ZcrlPortal.Models.UserProfile updatedProfile)
        {
            bool isOwner = (source.Id == (int)Profile["Id"]);
            string logContent = null;

            if ((updatedProfile.RelatedUser != null) && (source.RelatedUser.Login != updatedProfile.RelatedUser.Login))
            {
                logContent += getLogString("логін", source, updatedProfile, source.RelatedUser.Login, updatedProfile.RelatedUser.Login, isOwner); 
            }
            if (source.FirstName != updatedProfile.FirstName)
            {
                logContent += getLogString("ім'я", source, updatedProfile, source.FirstName, updatedProfile.FirstName, isOwner);
            }
            if (source.MiddleName != updatedProfile.MiddleName)
            {
                logContent += getLogString("ім'я по-батькові", source, updatedProfile, source.MiddleName, updatedProfile.MiddleName, isOwner);
            }
            if (source.LastName != updatedProfile.LastName)
            {
                logContent += getLogString("прізвище", source, updatedProfile, source.LastName, updatedProfile.LastName, isOwner);
            }
            if (source.JobTitle != updatedProfile.JobTitle)
            {
                logContent += getLogString("назву посади", source, updatedProfile, source.JobTitle, updatedProfile.JobTitle, isOwner);
            }
            if (source.TelephoneNumber != updatedProfile.TelephoneNumber)
            {
                logContent += getLogString("номер телефону", source, updatedProfile, source.TelephoneNumber, updatedProfile.TelephoneNumber, isOwner);
            }
            if (source.WorkLocation != updatedProfile.WorkLocation)
            {
                logContent += getLogString("кабінет", source, updatedProfile, source.WorkLocation, updatedProfile.WorkLocation, isOwner);
            }
            if ((!string.IsNullOrWhiteSpace(source.SiteAddress) || !string.IsNullOrWhiteSpace(updatedProfile.SiteAddress)) 
                && (source.SiteAddress != updatedProfile.SiteAddress))
            {
                logContent += getLogString("адресу веб-сайту", source, updatedProfile, source.SiteAddress, updatedProfile.SiteAddress, isOwner);
            }
            if (source.Sex != updatedProfile.Sex)
            {
                logContent += getLogString("пол", source, updatedProfile, source.Sex.ToString(), updatedProfile.Sex.ToString(), isOwner);
            }
            if ((!string.IsNullOrWhiteSpace(source.Email) || !string.IsNullOrWhiteSpace(updatedProfile.Email)) 
                && (source.Email != updatedProfile.Email))
            {
                logContent += getLogString("адресу электронної пошти", source, updatedProfile, source.Email, updatedProfile.Email, isOwner);
            }
            if ((!string.IsNullOrWhiteSpace(source.Education) || !string.IsNullOrWhiteSpace(updatedProfile.Education)) 
                && (source.Education != updatedProfile.Education))
            {
                logContent += getLogString("освіту", source, updatedProfile, source.Education, updatedProfile.Education, isOwner);
            }
            if ((updatedProfile.DataGroupId != null) && (source.DataGroupId != updatedProfile.DataGroupId))
            {
                string firstValue = (source.RelatedDepartment == null) ? null : source.RelatedDepartment.Name;
                logContent += getLogString("підрозділ", source, updatedProfile, firstValue, ZcrlGroupIndexer.GetDepById(updatedProfile.DataGroupId.Value), isOwner);
            }
            if ((updatedProfile.RelatedUser != null) && (source.RelatedUser.RoleId != updatedProfile.RelatedUser.RoleId))
            {
                logContent += getLogString("права", source, updatedProfile, source.RelatedUser.UserRole.DisplayName, ZcrlGroupIndexer.GetRoleById(updatedProfile.RelatedUser.RoleId), isOwner);
            }

            if(!string.IsNullOrWhiteSpace(logContent))
            {
                using(ZcrlContext zc = new ZcrlContext())
                {
                    zc.LogJournal.Add(new ZcrlPortal.Models.LogRecord() 
                    { 
                        RecordType = Models.LogRecordType.UserChanges, Content = logContent, СreatedDate = DateTime.Now 
                    });
                    zc.SaveChanges();
                }
            }
        }

        [Authorize]
        public ActionResult EditProfile(int? id)
        {

            ZcrlPortal.Models.UserProfile editableProfile = null;
            int editableProfileId;

            if (!id.HasValue || (!User.IsInRole("Administrators") && ((int)Profile["Id"] != id.Value)))
            {
                editableProfileId = (int)Profile["Id"];
            }
            else
            {
                editableProfileId = id.Value;
                ViewBag.ProfileId = editableProfileId;
            }

            using (zcrlDbContext = new ZcrlContext())
            {
                ViewBag.DepartmentList = (from d in zcrlDbContext.PortalDataGroups 
                                          where (d.RelatedGroup == Models.DataGroupType.UserDepartment) 
                                          select new ZcrlPortal.ViewModels.SelectListItem() { Value = d.Id, DisplayName = d.Name }).ToList();
                ViewBag.RoleList = (from r in zcrlDbContext.Roles select new ZcrlPortal.ViewModels.SelectListItem() { Value = r.Id, DisplayName = r.DisplayName }).ToList();

                editableProfile = (from p in zcrlDbContext.Profiles.Include("RelatedUser").Include("RelatedDepartment")
                                   where (p.Id == editableProfileId)
                                   select p).FirstOrDefault();

                if (editableProfile == null)
                {
                    return RedirectToAction("NotFound", "Error");
                }
            }
            return View(editableProfile);
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult EditProfile(ZcrlPortal.Models.UserProfile updatedProfile, HttpPostedFileBase photoFile)
        {
            int profileEditorId = (int)Profile["Id"];
            int? redirectProfileId = null;
            if ((updatedProfile.Id != profileEditorId) && !User.IsInRole("Administrators"))
            {
                return RedirectToAction("EditProfile");
            }

            if(updatedProfile.Id != profileEditorId)
            {
                redirectProfileId = updatedProfile.Id;
            }

            ZcrlPortal.Models.UserProfile requiredProfile;
            ZcrlPortal.Models.UserProfile existProfile;

            string error = ZcrlDataValidator.getProfileInputError(updatedProfile);
            if(!string.IsNullOrWhiteSpace(error))
            {
                TempData["Error"] = error;
                return RedirectToAction("EditProfile", new { id = redirectProfileId });
            }

            using (zcrlDbContext = new ZcrlContext())
            {
                // Профиль который необходимо изменить
                requiredProfile = (from p in zcrlDbContext.Profiles
                                   where (p.Id == updatedProfile.Id)
                                   select p).FirstOrDefault();
                
                if(updatedProfile.RelatedUser == null)
                {
                    existProfile = null;
                }
                else
                {
                    if(string.IsNullOrWhiteSpace(updatedProfile.RelatedUser.Login))
                    {
                        TempData["Error"] = "Ви не вказали логін";
                        return RedirectToAction("EditProfile", new { id = redirectProfileId });
                    }
                    string enteredLogin = updatedProfile.RelatedUser.Login.Trim();
                    // При изменении логина, ищем другой профиль с таким же логином
                    existProfile = (from p in zcrlDbContext.Profiles
                                    where ((p.RelatedUser.Login == enteredLogin) && (p.Id != updatedProfile.Id))
                                    select p).FirstOrDefault();
                }
                

                if (requiredProfile != null)
                {
                    if (User.IsInRole("Administrators") && existProfile != null)
                    {

ZcrlPortal/Views/UserProfile/ChangePassword.cshtml
@{
    ViewBag.Title = "Змінити пароль";
    Layout = "~/Views/Shared/_main.cshtml";

    int id = ViewBag.PassOwnerId;
}

<div class="editProfileContainer">
    @if (TempData["Error"] != null && !string.IsNullOrWhiteSpace((string)TempData["Error"]))
    {
        <div class="errorMessage">@TempData["Error"]</div>
    }
    
    @using (Html.BeginForm("ChangePassword", "UserProfile", FormMethod.Post, new { @class = "smart-green" }))
    {
        @Html.Hidden("id", id)
        <table>
            <tr>
                @if(!User.IsInRole("Administrators"))
                {
                    <th>Старий пароль:</th>
                    <td><input name="oldPass" type="password" /></td>
                }
            </tr>
            <tr>
                <th>Новий пароль:</th>
                <td><input name="newPass" type="password" /></td>
            </tr>
            <tr>
                <th>Підтвердіть пароль:</th>
                <td><input name="confirmNewPass" type="password" /></td>
            </tr>
            <tr>
                <th colspan="2" style="text-align: center;"><button type="submit">Змінити пароль</button></th>
            </tr>
        </table>
    }
</div>

ZcrlPortal/Views/UserProfile/EditProfile.cshtml
@using ZcrlPortal.Models
@using ZcrlPortal.Controllers
@model ZcrlPortal.Models.UserProfile
@{
    int? editableProfileId = null;

    if(ViewBag.ProfileId != null)
    {
        editableProfileId = ViewBag.ProfileId;
    }
    
    ViewBag.Title = "Редагування профіля";
    Layout = "~/Views/Shared/_main.cshtml";
    bool isSuccess = false;
    string errorMessage = null;
    if ((ViewBag.editProfileSuccess != null) && ViewBag.editProfileSuccess)
    {
        isSuccess = true;
    }
    else if (TempData["Success"] != null)
    {
        isSuccess = true;
    }

    if (ViewBag.editProfilerError != null)
    {
        errorMessage = ViewBag.editProfilerError;
    }
    else if (TempData["Error"] != null)
    {
        errorMessage = TempData["Error"].ToString();
    }
}

<div class="editProfileContainer">
    @if (isSuccess)
    {
        <div class="successMessage">Данні профіля успішно змінені!</div>
    }
    @if (errorMessage != null)
    {
        <div class="errorMessage">@errorMessage</div>
    }


    <div style="clear:both"></div>
    <div class="userData">
        @using (Html.BeginForm("EditProfile", "UserProfile", FormMethod.Post, new { @class = "smart-green", enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(m => m.Id)
            <table>
                @if (User.IsInRole("Administrators"))
                {
                    <tr>
                        <th>Логін: </th>
                        <td>@Html.TextBoxFor(m => m.RelatedUser.Login, new { placeholder = "Введіть логін" })</td>
                    </tr>
                }
                <tr>
                    <th>Прізвище: </th>
                    <td>@Html.TextBoxFor(m => m.LastName, new { placeholder = "Введіть прізвище" })</td>
                </tr>
                <tr>
                    <th>Ім'я: </th>
                    <td>@Html.TextBoxFor(m => m.FirstName, new { placeholder = "Введіть ім'я" })</td>
                </tr>
                <tr>
                    <th>Ім'я по-батькові: </th>
                    <td>@Html.TextBoxFor(m => m.MiddleName, new { placeholder = "Введіть ім'я по-батькові" })</td>
                </tr>
                <tr>
                    <th>Стать: </th>
                    <td>@Html.RadioButtonFor(m => m.Sex, UserSex.Male) Чоловіча  @Html.RadioButtonFor(k => k.Sex, UserSex.Female) Жіноча</td>
                </tr>
                <tr>
                    <th colspan="2"><br /></th>
                </tr>
                <tr>
                    <th>Пароль: </th>
                    <td><a href="@Url.Action("ChangePassword", "UserProfile", new { id = ViewBag.ProfileId })">Змінити пароль</a></td>
                </tr>
                <tr>
                    <th colspan="2"><br /></th>
                </tr>
                <tr>
                    <th>Назва посади: </th>
                    <td>@Html.TextBoxFor(m => m.JobTitle, new { placeholder = "Введіть посаду" })</td>
                </tr>
                <tr>
                    <th>Робочий телефон: </th>
                    <td>@Html.TextBoxFor(m => m.TelephoneNumber, new { placeholder = "Введіть номер телефону" })</td>
                </tr>
                <tr>
                    <th>Номер кабінету: </th>
                    <td>@Html.TextBoxFor(m => m.WorkLocation, new { placeholder = "Вкажіть де Вас можна знайти" })</td>
                </tr>
                <tr>
                    <th>Фотографія: </th>
                    <td><input type="text" class="ufName" readonly="readonly" id="ufName" /> <div class="uploadFileContainer"><span>Вибрати файл</span><input name="photoFile" id="photoFile" type="file" onchange="GetUploadFileName(this)" /></div></td>
                </tr>
                <tr>
                    <th>Освіта: </th>
                    <td>@Html.TextBoxFor(m => m.Education, new { placeholder = "Що ви закінчили?" })</td>
                </tr>
                <tr>
                    <th>Email: </th>
                    <td>@Html.TextBoxFor(m => m.Email, new { placeholder = "Введіть Email" })</td>
                </tr>
                <tr>
                    <th>Веб-сайт: </th>
                    <td>@Html.TextBoxFor(m => m.SiteAddress, new { placeholder = "Адреса веб-сайту" })</td>
                </tr>
                @if (User.IsInRole("Administrators"))
                {
                    <tr>
                        <th>Права користувача: </th>
                        <td>@Html.DropDownListFor(m => m.RelatedUser.RoleId, new SelectList(ViewBag.RoleList, "Value", "DisplayName"))</td>
                    </tr>
                    <tr>
                        <th>Группа користувача: </th>
                        <td>@Html.DropDownListFor(m => m.DataGroupId, new SelectList(ViewBag.DepartmentList, "Value", "DisplayName"))</td>
                    </tr>
                    <tr>
                        <th>Відобразити користувача: </th>
                        <td>@Html.CheckBoxFor(m => m.IsPublicated) Так</td>
                    </tr>
                    <tr>
                        <th>Пріорітет відображення: </th>
                        <td>@Html.TextBoxFor(m => m.ViewPriority, new { placeholder = "Номер порядку відображення в группі" })</td>
                    </tr>
                }
                <tr>
                    <th colspan="2" class="buttonRow"><button type="submit">Змінити данні</button></th>
                </tr>
            </table>
        }

    </div>

    <div class="userPhoto">
        @if (!string.IsNullOrWhiteSpace(Model.PhotoFileName))
        {
            <img src="@Url.Content(MasterController.UPLOADPHOTO_DIR + @"\" + Model.PhotoFileName)" />
        }
        else
        {
            if (Model.Sex == UserSex.Male)
            {
                <img src="@Url.Content(@"~\UserPhotos\non_m.png")" />
            }
            else
            {
                <img src="@Url.Content(@"~\UserPhotos\non_f.png")" />
            }
        }
        <a href="@Url.Action("DeletePhoto", "UserProfile", new { id = editableProfileId })" onclick="return confirm('Вы впевнені, що хочете видалити фото?')">Видалити фото</a>
    </div>

    <div style="clear:both"></div>

    <div class="userBio">
        @using (Html.BeginForm("EditUserBiography", "UserProfile", FormMethod.Post))
        {
            @Html.HiddenFor(m => m.Id)
            <h1>Біографія</h1>
            @Html.TextAreaFor(m => m.AboutMe)
            <h1><button type="submit">Змінити біографію</button></h1>
        }
    </div>

    <br /><br />

</div>

<script>
    jQuery(function ($) {
        $("#TelephoneNumber").mask("(061) 999-99-99");
    });
</script>

<script>
    CKEDITOR.replace('AboutMe', {
         toolbar: [
         { name: 'clipboard', groups: ['clipboard', 'undo'], items: ['Cut', 'Copy', 'Paste', '-', 'Undo', 'Redo'] },
         { name: 'editing', groups: ['find', 'selection', 'spellchecker'], items: ['Find', 'Replace', '-', 'Maximize'] },
         '/',
         { name: 'basicstyles', groups: ['basicstyles', 'cleanup'], items: ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-','RemoveFormat'] },
         { name: 'paragraph', groups: ['list', 'indent', 'blocks', 'align', 'bidi'], items: ['NumberedList', 'BulletedList', '-', 'Blockquote'] },
         { name: 'links', items: ['Link', 'Image', 'Anchor', 'Table', 'TextColor'] },
         { name: 'styles', items: ['Format'] },
         ],
        filebrowserImageUploadUrl: '@Url.Action("UploadImage", "Editor")',
        format_tags: 'p;h2',
        image2_alignClasses: ['image-left', 'image-center', 'image-right'],
    });
</script>